version: '3.8'

# Example application of the cron image
services:
  cron:
    build:
      context: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  hello:
    image: hello-world
    restart: "no"
    labels:
      - "cron.schedule=* * * * * "
  
  hello2:
    image: hello-world
    restart: "no"
    labels:
      - "cron.schedule=* * * * * "